import { H1 } from "@/components/ui";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "EMORYA | Become Ambassador",
  description: "Generated by create next app",
};

export default function BecomeAmbassadorPage() {
  return (
    <main className="flex min-h-[calc(100vh-501px)] items-center justify-center">
      <H1 className="text-center">
        Become Ambassador <br /> Page In Progess...
      </H1>
    </main>
  );
}
