import { Footer, Navbar } from "@/components/layout";
import type { Metadata } from "next";
// import { GoogleTagManager, GoogleAnalytics } from "@next/third-parties/google";
import { ServiceWorkerRegistration } from "@/components/ServiceWorkerRegistration";
import { Plus_Jakarta_Sans } from "next/font/google";

import "./globals.css";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  manifest: "/manifest.json",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/icons/favicon-light.ico",
        href: "/icons/favicon-light.ico",
        type: "image/x-icon",
        rel: "icon",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/icons/favicon-dark.ico",
        href: "/icons/favicon-dark.ico",
        type: "image/x-icon",
        rel: "icon",
      },
    ],
    apple: {
      url: "/icons/apple-icon.png",
    },
  },
  title: "EMORYA",
  description: "Emorya generated by create next app",
  appleWebApp: {
    title: "Emorya",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <GoogleAnalytics gaId="" /> */}
      {/* <GoogleTagManager gtmId="" /> */}
      <body
        className={`${plusJakarta.variable} bg-purple-primary font-plusJakarta scroll-smooth antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        <ServiceWorkerRegistration />
      </body>
    </html>
  );
}
